input_method = "smart"
enabled = true
output_mode = "unicodedungsan"
free_tone_placement = true
auto_detect_lang = true
enable_per_app = true
ime_mode = "nonpreedit"
tone_style = "classic"

[app_configs.alacritty]
ime_mode = "nonpreedit"

[app_configs.footclient]
ime_mode = "nonpreedit"

[app_configs.foot]
ime_mode = "nonpreedit"

[app_configs.code]
ime_mode = "nonpreedit"

[app_configs.firefox]
ime_mode = "nonpreedit"

[app_configs.code-oss]
ime_mode = "nonpreedit"

[app_configs.wezterm]
ime_mode = "nonpreedit"

[app_configs."com.mitchellh.ghostty"]
ime_mode = "nonpreedit"

[app_configs.kitty]
ime_mode = "nonpreedit"

[app_configs.google-chrome]
ime_mode = "nonpreedit"

[app_configs.chromium-browser]
ime_mode = "nonpreedit"

[site_configs]
