// SPDX-License-Identifier: GPL-3.0-or-later OR Commercial
// Copyright (c) 2024-2026 vi-im contributors
//! System-tray icon (StatusNotifierItem), fcitx-style. Runs in its own thread
//! (ksni spawns a DBus loop), shows the live method/on-off, and offers a menu:
//! switch method, toggle IME, open the QML config window, quit.
//!
//! Menu actions mutate `setting.conf` through `ConfigManager` — the daemon
//! already watches that file (inotify) and live-reloads, so the tray needs no
//! direct channel into the IME thread. The floating config window is the
//! separate `vi-settings` QML launcher (kept intact — the tray only spawns it).

use std::path::PathBuf;
use std::process::Command;
use std::thread;
use std::time::Duration;

use tracing::{info, warn};

use crate::config::{ConfigManager, ImeMode, InputMethod};
use crate::tray_icon;

/// Icon SVGs baked into the binary (generated by `scripts/gen-icons.py`) —
/// zero-config: the daemon installs them into the user's icon theme itself,
/// no separate `make install-icons` step to forget. This covers GTK/Qt-
/// based bars that do freedesktop icon-theme lookups by name; bars that
/// don't (several minimal wlroots panels) get `icon_pixmap()` instead
/// (`tray_icon.rs` — raw ARGB32, no theme lookup needed at all).
const ICON_ON_SVG: &str = include_str!("../../../assets/icons/vi-im.svg");
const ICON_OFF_SVG: &str = include_str!("../../../assets/icons/vi-im-off.svg");

/// Freedesktop icon-theme name for each state — `icon_name()` returns one
/// of these; the actual bytes live wherever `install_icons` put them.
const ICON_ON: &str = "vi-im";
const ICON_OFF: &str = "vi-im-off";

/// Drop the baked-in SVGs into `~/.local/share/icons/hicolor/scalable/apps/`
/// (XDG_DATA_HOME-aware) so `icon_name()` resolves through the normal
/// freedesktop icon-theme lookup that every StatusNotifierHost implements.
/// Idempotent and non-fatal — a write failure just means the host falls
/// back to `icon_pixmap()` (raw bytes, always available regardless).
fn install_icons() {
    let base = std::env::var("XDG_DATA_HOME")
        .map(PathBuf::from)
        .or_else(|_| std::env::var("HOME").map(|h| PathBuf::from(h).join(".local/share")));
    let Ok(base) = base else { return };
    let dir = base.join("icons/hicolor/scalable/apps");
    if std::fs::create_dir_all(&dir).is_err() {
        return;
    }
    for (name, svg) in [(ICON_ON, ICON_ON_SVG), (ICON_OFF, ICON_OFF_SVG)] {
        let path = dir.join(format!("{name}.svg"));
        if std::fs::write(&path, svg).is_err() {
            warn!("[TRAY] could not install icon {path:?}");
        }
    }
}

/// Tray state source: reads/writes the on-disk config the daemon watches.
pub struct ViTray {
    config_path: PathBuf,
    /// Path to the `vi-settings` launcher (QML config window), if found.
    settings_exe: Option<PathBuf>,
    /// Live method — set in activate callback, ksni re-reads menu() after.
    current_method: InputMethod,
    current_mode: ImeMode,
    current_enabled: bool,
}

impl ViTray {
    /// Persist method to config and update live state.
    /// ksni re-reads menu() after the activate callback returns,
    /// so the radio selection updates immediately.
    fn set_method(&mut self, method: InputMethod) {
        self.current_method = method;
        if let Ok(mut m) = ConfigManager::new(Some(self.config_path.clone())) {
            m.setting_mut().input_method = method;
            let _ = m.save();
            info!("[TRAY] method → {method}");
        }
    }

    /// Persist display mode (Preedit/NonPreedit) — same flow as set_method.
    fn set_mode(&mut self, mode: ImeMode) {
        self.current_mode = mode;
        if let Ok(mut m) = ConfigManager::new(Some(self.config_path.clone())) {
            m.setting_mut().ime_mode = mode;
            let _ = m.save();
            info!("[TRAY] ime_mode → {mode:?}");
        }
    }

    fn toggle(&mut self) {
        self.current_enabled = !self.current_enabled;
        if let Ok(mut m) = ConfigManager::new(Some(self.config_path.clone())) {
            m.setting_mut().enabled = self.current_enabled;
            let _ = m.save();
            info!("[TRAY] IME {}", if self.current_enabled { "enabled" } else { "disabled" });
        }
    }

    fn open_settings(&self) {
        match &self.settings_exe {
            Some(exe) => {
                if let Err(e) = Command::new(exe).spawn() {
                    warn!("[TRAY] cannot launch settings {exe:?}: {e}");
                }
            }
            None => warn!("[TRAY] vi-settings launcher not found next to binary"),
        }
    }
}

impl ksni::Tray for ViTray {
    fn id(&self) -> String {
        "vi-im".into()
    }

    fn icon_name(&self) -> String {
        // 'V' blue tile when Vietnamese input is on, 'E' when off — the
        // glyph itself says the mode, no need to read the tooltip.
        if self.current_enabled { ICON_ON.into() } else { ICON_OFF.into() }
    }

    fn icon_pixmap(&self) -> Vec<ksni::Icon> {
        // Belt-and-suspenders (see module doc): panels that never resolve
        // `icon_name` through a theme still get a correct icon from this.
        tray_icon::pixmap(self.current_enabled)
    }

    fn title(&self) -> String {
        format!("vi-im · {} · {}", self.current_method, if self.current_enabled { "Bật" } else { "Tắt" })
    }

    fn tool_tip(&self) -> ksni::ToolTip {
        ksni::ToolTip {
            title: format!("vi-im · {}", self.current_method),
            description: if self.current_enabled { "Đang bật".into() } else { "Đang tắt".into() },
            icon_name: self.icon_name(),
            icon_pixmap: self.icon_pixmap(),
        }
    }

    fn menu(&self) -> Vec<ksni::MenuItem<Self>> {
        use ksni::menu::{CheckmarkItem, MenuItem, RadioGroup, RadioItem, StandardItem};

        // Native DBusMenu radio/checkbox semantics (toggle-type + toggle-
        // state properties), NOT a "✓" hand-appended to the label text.
        // Some minimal tray hosts diff only the properties they understand
        // for redraw — embedding the mark in plain label text worked on
        // some hosts and silently froze on others; RadioGroup/CheckmarkItem
        // is the standards-compliant construct every DBusMenu host renders
        // and refreshes correctly (this is also what ksni's own
        // `update_immediately` mechanism is designed around).
        const METHODS: [InputMethod; 3] = [InputMethod::Telex, InputMethod::Vni, InputMethod::Smart];
        let method_selected = METHODS.iter().position(|m| *m == self.current_method).unwrap_or(0);

        const MODES: [ImeMode; 2] = [ImeMode::Preedit, ImeMode::NonPreedit];
        let mode_selected = MODES.iter().position(|m| *m == self.current_mode).unwrap_or(0);

        vec![
            RadioGroup {
                selected: method_selected,
                select: Box::new(|t: &mut Self, idx| t.set_method(METHODS[idx])),
                options: vec![
                    RadioItem { label: "Telex".into(), ..Default::default() },
                    RadioItem { label: "VNI".into(), ..Default::default() },
                    RadioItem { label: "Tự do".into(), ..Default::default() },
                ],
            }
            .into(),
            MenuItem::Separator,
            RadioGroup {
                selected: mode_selected,
                select: Box::new(|t: &mut Self, idx| t.set_mode(MODES[idx])),
                options: vec![
                    RadioItem { label: "Preedit (gạch chân)".into(), ..Default::default() },
                    RadioItem { label: "NonPreedit (gõ thẳng)".into(), ..Default::default() },
                ],
            }
            .into(),
            MenuItem::Separator,
            CheckmarkItem {
                label: if self.current_enabled {
                    "🟢 Đang bật".into()
                } else {
                    "🔴 Đang tắt".into()
                },
                checked: self.current_enabled,
                activate: Box::new(|t: &mut Self| t.toggle()),
                ..Default::default()
            }
            .into(),
            MenuItem::Separator,
            StandardItem {
                label: "Cài đặt…".into(),
                activate: Box::new(|t: &mut Self| t.open_settings()),
                ..Default::default()
            }
            .into(),
            StandardItem {
                label: "Thoát vi-im".into(),
                activate: Box::new(|_| std::process::exit(0)),
                ..Default::default()
            }
            .into(),
        ]
    }
}

/// Read the tray-relevant trio from disk.
fn read_state(path: &PathBuf) -> (InputMethod, ImeMode, bool) {
    ConfigManager::new(Some(path.clone()))
        .map(|m| {
            let s = m.setting();
            (s.input_method, s.ime_mode, s.enabled)
        })
        .unwrap_or((InputMethod::Telex, ImeMode::Preedit, true))
}

/// Register the tray (fcitx-style). Non-fatal: if no StatusNotifierHost is
/// running (bar without tray support), this simply shows no icon — the IME
/// keeps working. `settings_exe` is the vi-settings launcher for the menu.
pub fn spawn(config_path: PathBuf, settings_exe: Option<PathBuf>) {
    install_icons();
    let (current_method, current_mode, current_enabled) = read_state(&config_path);
    let tray = ViTray {
        config_path: config_path.clone(),
        settings_exe,
        current_method,
        current_mode,
        current_enabled,
    };
    let service = ksni::TrayService::new(tray);
    let handle = service.handle();
    service.spawn();

    // Reverse sync: the tray's own clicks update it via ksni's re-read, but
    // changes from the settings GUI / CLI / file edits only land on disk.
    // Poll the config and push differences into ksni (handle.update emits
    // the DBus layout change → radio/checkbox state and title follow live).
    thread::spawn(move || {
        let mut last = read_state(&config_path);
        loop {
            thread::sleep(Duration::from_secs(2));
            let now = read_state(&config_path);
            if now != last {
                last = now;
                handle.update(|t: &mut ViTray| {
                    t.current_method = now.0;
                    t.current_mode = now.1;
                    t.current_enabled = now.2;
                });
            }
        }
    });
    info!("[TRAY] StatusNotifierItem registered (fcitx-style tray + menu)");
}
