// SPDX-License-Identifier: GPL-3.0-only
// Copyright (c) 2024-2026 vi-im contributors
//! System-tray icon (StatusNotifierItem) — ayatana-appindicator (libappindicator3)
//! Runs GTK main loop in a dedicated thread. Provides better panel compatibility
//! (warp-taskbar, waybar, etc.) than raw ksni.

use std::path::PathBuf;
use std::sync::mpsc::{Sender, channel};
use std::sync::{Arc, Mutex};
use std::thread;
use std::time::Duration;

use appindicator3::prelude::AppIndicatorExt;
use appindicator3::{Indicator, IndicatorCategory, IndicatorStatus};
use gtk::prelude::*;
use gtk::{CheckMenuItem, Menu, MenuItem, RadioMenuItem, SeparatorMenuItem};
use tracing::{info, warn};

use crate::config::{ConfigManager, ImeMode, InputMethod};

const ICON_ON: &str = "vi-im";
const ICON_OFF: &str = "vi-im-off";

/// Icon SVGs baked into the binary (generated by `scripts/gen-icons.py`).
const ICON_ON_SVG: &str = include_str!("../../../assets/icons/vi-im.svg");
const ICON_OFF_SVG: &str = include_str!("../../../assets/icons/vi-im-off.svg");

/// Tray state shared between the GTK thread and the daemon.
#[derive(Clone)]
struct TrayState {
    current_method: InputMethod,
    current_mode: ImeMode,
    current_enabled: bool,
}

impl Default for TrayState {
    fn default() -> Self {
        Self {
            current_method: InputMethod::Telex,
            current_mode: ImeMode::Preedit,
            current_enabled: true,
        }
    }
}

/// Install the baked SVG icons into a FLAT directory and return that
/// directory's path.
///
/// libappindicator's `set_icon_theme_path` — confirmed against the crate's
/// own example (`appindicator3-0.3.0/examples/simple_client.rs`) — expects
/// a plain folder containing `<name>.svg`/`<name>.png` directly, NOT a
/// freedesktop hicolor hierarchy (`hicolor/scalable/apps/…`). Pointing it
/// at the hicolor tree renders as a blank/placeholder icon: the lookup
/// finds nothing at `<path>/vi-im.svg` because the real file sits one
/// level deeper. Kept out of `~/.local/share/icons` entirely to avoid
/// mixing conventions.
fn install_icons() -> Option<PathBuf> {
    let base = std::env::var("XDG_DATA_HOME")
        .map(PathBuf::from)
        .or_else(|_| std::env::var("HOME").map(|h| PathBuf::from(h).join(".local/share")))
        .ok()?;
    let dir = base.join("vi-im/icons");
    std::fs::create_dir_all(&dir).ok()?;
    for (name, svg) in [(ICON_ON, ICON_ON_SVG), (ICON_OFF, ICON_OFF_SVG)] {
        let path = dir.join(format!("{name}.svg"));
        if std::fs::write(&path, svg).is_err() {
            warn!("[TRAY] could not install icon {:?}", path);
        } else {
            info!("[TRAY] installed icon {:?} ({} bytes)", path, svg.len());
        }
    }
    Some(dir)
}

/// Read tray-relevant config from disk.
fn read_state(path: &PathBuf) -> (InputMethod, ImeMode, bool) {
    ConfigManager::new(Some(path.clone()))
        .map(|m| {
            let s = m.setting();
            (s.input_method, s.ime_mode, s.enabled)
        })
        .unwrap_or((InputMethod::Telex, ImeMode::Preedit, true))
}

/// Convert InputMethod to display label.
fn method_label(method: InputMethod) -> &'static str {
    match method {
        InputMethod::Telex => "Telex",
        InputMethod::Vni => "VNI",
        InputMethod::Smart => "Tự do",
    }
}

/// Convert ImeMode to display label.
fn mode_label(mode: ImeMode) -> &'static str {
    match mode {
        ImeMode::Preedit => "Preedit (gạch chân)",
        ImeMode::NonPreedit => "NonPreedit (gõ thẳng)",
    }
}

/// Tray update signal type.
#[derive(Debug, Clone, Copy)]
pub(crate) struct UpdateSignal;

/// Persist one config field, log, then rebuild the menu + icon IMMEDIATELY
/// (synchronously, same GTK thread — no DBus round-trip, no dependency on
/// a host correctly implementing LayoutUpdated/PropertiesChanged, which is
/// exactly the class of bug that made the old ksni-based tray's checkmarks
/// freeze on some panels).
fn refresh(
    indicator: &Indicator,
    state: &Arc<Mutex<TrayState>>,
    config_path: &PathBuf,
    settings_exe: &Option<PathBuf>,
) {
    let (method, mode, enabled) = read_state(config_path);
    {
        let mut guard = state.lock().unwrap();
        guard.current_method = method;
        guard.current_mode = mode;
        guard.current_enabled = enabled;
    }
    indicator.set_icon_full(if enabled { ICON_ON } else { ICON_OFF }, "vi-im");
    let menu = build_menu(
        indicator,
        state,
        config_path,
        settings_exe,
        method,
        mode,
        enabled,
    );
    indicator.set_menu(Some(&menu));
}

/// Build the full tray menu for the given state. Every menu item writes
/// straight to `setting.conf` (the daemon watches it via inotify and
/// live-reloads — same flow the settings GUI and CLI use) and then calls
/// [`refresh`] itself, so the widget the user is looking at updates in the
/// same click, not on the next 2s poll.
#[allow(clippy::too_many_arguments)]
fn build_menu(
    indicator: &Indicator,
    state: &Arc<Mutex<TrayState>>,
    config_path: &PathBuf,
    settings_exe: &Option<PathBuf>,
    method: InputMethod,
    mode: ImeMode,
    enabled: bool,
) -> Menu {
    let menu = Menu::new();

    // ── Kiểu gõ: Telex / VNI / Tự do (radio group) ──
    let methods = [InputMethod::Telex, InputMethod::Vni, InputMethod::Smart];
    let mut first_method_item: Option<RadioMenuItem> = None;
    for m in methods {
        let item = match &first_method_item {
            None => RadioMenuItem::builder()
                .label(method_label(m))
                .active(m == method)
                .build(),
            Some(first) => {
                let it = RadioMenuItem::with_label_from_widget(first, Some(method_label(m)));
                it.set_active(m == method);
                it
            }
        };
        let indicator = indicator.clone();
        let state = Arc::clone(state);
        let config_path = config_path.clone();
        let settings_exe = settings_exe.clone();
        item.connect_activate(move |it| {
            if !it.is_active() {
                return;
            }
            if let Ok(mut cm) = ConfigManager::new(Some(config_path.clone())) {
                cm.setting_mut().input_method = m;
                let _ = cm.save();
                info!("[TRAY] method → {m:?}");
                crate::notify::popup("vi-ime", &format!("🔤 {}", method_label(m)));
            }
            refresh(&indicator, &state, &config_path, &settings_exe);
        });
        if first_method_item.is_none() {
            first_method_item = Some(item.clone());
        }
        menu.append(&item);
    }

    menu.append(&SeparatorMenuItem::new());

    // ── Chế độ hiển thị: Preedit / NonPreedit (radio group) ──
    let modes = [ImeMode::Preedit, ImeMode::NonPreedit];
    let mut first_mode_item: Option<RadioMenuItem> = None;
    for mo in modes {
        let item = match &first_mode_item {
            None => RadioMenuItem::builder()
                .label(mode_label(mo))
                .active(mo == mode)
                .build(),
            Some(first) => {
                let it = RadioMenuItem::with_label_from_widget(first, Some(mode_label(mo)));
                it.set_active(mo == mode);
                it
            }
        };
        let indicator = indicator.clone();
        let state = Arc::clone(state);
        let config_path = config_path.clone();
        let settings_exe = settings_exe.clone();
        item.connect_activate(move |it| {
            if !it.is_active() {
                return;
            }
            if let Ok(mut cm) = ConfigManager::new(Some(config_path.clone())) {
                cm.setting_mut().ime_mode = mo;
                let _ = cm.save();
                info!("[TRAY] ime_mode → {mo:?}");
                crate::notify::popup("vi-ime", &format!("📋 {}", mode_label(mo)));
            }
            refresh(&indicator, &state, &config_path, &settings_exe);
        });
        if first_mode_item.is_none() {
            first_mode_item = Some(item.clone());
        }
        menu.append(&item);
    }

    menu.append(&SeparatorMenuItem::new());

    // ── Bật / Tắt ──
    let toggle_item = CheckMenuItem::with_label(if enabled {
        "🟢 Đang bật"
    } else {
        "🔴 Đang tắt"
    });
    toggle_item.set_active(enabled);
    {
        let indicator = indicator.clone();
        let state = Arc::clone(state);
        let config_path = config_path.clone();
        let settings_exe = settings_exe.clone();
        toggle_item.connect_toggled(move |it| {
            let now_enabled = it.is_active();
            if let Ok(mut cm) = ConfigManager::new(Some(config_path.clone())) {
                cm.setting_mut().enabled = now_enabled;
                let _ = cm.save();
                info!(
                    "[TRAY] IME {}",
                    if now_enabled { "enabled" } else { "disabled" }
                );
                crate::notify::popup(
                    "vi-ime",
                    if now_enabled {
                        "🟢 Bật"
                    } else {
                        "🔴 Tắt"
                    },
                );
            }
            refresh(&indicator, &state, &config_path, &settings_exe);
        });
    }
    menu.append(&toggle_item);

    // AppIndicator's protocol reserves plain LEFT-click for opening the
    // menu — every host that implements the spec does this, it is not
    // configurable from our side (unlike the old GtkStatusIcon API, which
    // did have a separate "activate" signal). The one quick-toggle gesture
    // the spec DOES define is "secondary activate" (conventionally
    // middle-click / scroll-click on most panels, Noctalia included) — we
    // point it at the same toggle_item so it fires the exact same on/off
    // logic as clicking the menu entry.
    indicator.set_secondary_activate_target(Some(&toggle_item));

    menu.append(&SeparatorMenuItem::new());

    // ── Tính năng: Autocorrect / Emoji / Clipboard Convert ──
    {
        let autocorrect_item = CheckMenuItem::with_label("✅ Tự sửa lỗi chính tả");
        if let Ok(cm) = ConfigManager::new(Some(config_path.clone())) {
            autocorrect_item.set_active(cm.setting().autocorrect);
        }
        {
            let config_path = config_path.clone();
            autocorrect_item.connect_toggled(move |it| {
                if let Ok(mut cm) = ConfigManager::new(Some(config_path.clone())) {
                    cm.setting_mut().autocorrect = it.is_active();
                    let _ = cm.save();
                    info!("[TRAY] autocorrect → {}", it.is_active());
                }
            });
        }
        menu.append(&autocorrect_item);

        let emoji_item = CheckMenuItem::with_label("😀 Emoji (shortcode)");
        if let Ok(cm) = ConfigManager::new(Some(config_path.clone())) {
            emoji_item.set_active(cm.setting().emoji);
        }
        {
            let config_path = config_path.clone();
            emoji_item.connect_toggled(move |it| {
                if let Ok(mut cm) = ConfigManager::new(Some(config_path.clone())) {
                    cm.setting_mut().emoji = it.is_active();
                    let _ = cm.save();
                    info!("[TRAY] emoji → {}", it.is_active());
                }
            });
        }
        menu.append(&emoji_item);

        let clipboard_item = CheckMenuItem::with_label("📋 Chuyển đổi clipboard");
        if let Ok(cm) = ConfigManager::new(Some(config_path.clone())) {
            clipboard_item.set_active(cm.setting().clipboard_convert);
        }
        {
            let config_path = config_path.clone();
            clipboard_item.connect_toggled(move |it| {
                if let Ok(mut cm) = ConfigManager::new(Some(config_path.clone())) {
                    cm.setting_mut().clipboard_convert = it.is_active();
                    let _ = cm.save();
                    info!("[TRAY] clipboard_convert → {}", it.is_active());
                }
            });
        }
        menu.append(&clipboard_item);
    }

    menu.append(&SeparatorMenuItem::new());

    // ── Cài đặt / Thoát ──
    let settings_item = MenuItem::with_label("Cài đặt…");
    {
        let settings_exe = settings_exe.clone();
        settings_item.connect_activate(move |_| match &settings_exe {
            Some(exe) => {
                if let Err(e) = std::process::Command::new(exe).spawn() {
                    warn!("[TRAY] cannot launch settings {exe:?}: {e}");
                }
            }
            None => warn!("[TRAY] vi-settings launcher not found next to binary"),
        });
    }
    menu.append(&settings_item);

    let quit_item = MenuItem::with_label("Thoát vi-im");
    quit_item.connect_activate(|_| std::process::exit(0));
    menu.append(&quit_item);

    menu.show_all();
    menu
}

/// Spawn the ayatana-appindicator tray in a dedicated GTK thread.
/// Returns a `Sender` that can be used to request updates from the daemon.
pub fn spawn(config_path: PathBuf, settings_exe: Option<PathBuf>) -> Sender<UpdateSignal> {
    // Install icons FIRST so they're available for icon-theme lookup.
    // Flat directory (see install_icons doc) — libappindicator's own path,
    // not the freedesktop hicolor tree.
    let icon_dir = install_icons();

    let (current_method, current_mode, current_enabled) = read_state(&config_path);
    info!(
        "[TRAY] Initial state: method={:?} mode={:?} enabled={}",
        current_method, current_mode, current_enabled
    );
    info!("[TRAY] Config path: {:?}", config_path);

    // Shared state between daemon and GTK thread.
    let state = Arc::new(Mutex::new(TrayState {
        current_method,
        current_mode,
        current_enabled,
    }));

    // Channel for daemon to request updates. `update_tx` itself is returned
    // to the caller below; the GTK thread gets its own clone so both sides
    // can send without fighting over ownership.
    let (update_tx, update_rx) = channel::<UpdateSignal>();
    let update_tx_for_thread = update_tx.clone();
    let state_for_gtk = Arc::clone(&state);
    let config_path_for_gtk = config_path.clone();
    let settings_exe_for_gtk = settings_exe.clone();
    let icon_dir_for_gtk = icon_dir.clone();

    // GTK thread: runs the GTK main loop and owns the Indicator.
    thread::Builder::new()
        .name("vi-tray-gtk".into())
        .spawn(move || {
            // Initialize GTK in this thread.
            if gtk::init().is_err() {
                warn!("[TRAY] Failed to initialize GTK");
                return;
            }

            // Read initial state for the indicator.
            let initial_state = {
                let guard = state_for_gtk.lock().unwrap();
                guard.clone()
            };

            // Create the indicator.
            let indicator = Indicator::new(
                "vi-im",
                if initial_state.current_enabled {
                    ICON_ON
                } else {
                    ICON_OFF
                },
                IndicatorCategory::ApplicationStatus,
            );
            indicator.set_status(IndicatorStatus::Active);
            // ONE call — a second call would silently replace the first
            // (libappindicator takes a single search path, not a list).
            // Falls back to the system hicolor "input-keyboard" glyph
            // (still set as the Indicator's icon_name below) if we
            // couldn't create our own icon dir for some reason.
            if let Some(dir) = &icon_dir_for_gtk {
                indicator.set_icon_theme_path(dir.to_str().unwrap_or(""));
            }

            // Build the initial menu.
            let menu = build_menu(
                &indicator,
                &state_for_gtk,
                &config_path_for_gtk,
                &settings_exe_for_gtk,
                initial_state.current_method,
                initial_state.current_mode,
                initial_state.current_enabled,
            );
            indicator.set_menu(Some(&menu));

            // Set initial icon.
            indicator.set_icon_full(
                if initial_state.current_enabled {
                    ICON_ON
                } else {
                    ICON_OFF
                },
                "vi-im",
            );

            info!("[TRAY] Indicator created and menu set");

            // Channel to signal the GTK thread to update the indicator.
            let (gtk_update_tx, gtk_update_rx) =
                glib::MainContext::channel(glib::Priority::DEFAULT);

            // Spawn a thread to bridge the daemon's update channel to GTK's channel.
            let state_for_bridge = Arc::clone(&state_for_gtk);
            let config_path_for_bridge = config_path_for_gtk.clone();
            thread::spawn(move || {
                while update_rx.recv().is_ok() {
                    // Read latest state from disk.
                    let (method, mode, enabled) = read_state(&config_path_for_bridge);
                    let mut guard = state_for_bridge.lock().unwrap();
                    guard.current_method = method;
                    guard.current_mode = mode;
                    guard.current_enabled = enabled;
                    drop(guard);
                    // Signal GTK thread to update.
                    let _ = gtk_update_tx.send(());
                }
            });

            // Handle updates in GTK thread. Own clones so the ORIGINAL
            // config_path_for_gtk/settings_exe_for_gtk/state_for_gtk/indicator
            // stay available below for the poller thread + the final
            // `gtk::main()` call — a plain `move` closure would otherwise
            // consume them here and strand the code after it.
            let config_path_for_attach = config_path_for_gtk.clone();
            let settings_exe_for_attach = settings_exe_for_gtk.clone();
            let state_for_attach = Arc::clone(&state_for_gtk);
            let indicator_for_attach = indicator.clone();
            gtk_update_rx.attach(None, move |_| {
                let guard = state_for_attach.lock().unwrap();
                let method = guard.current_method;
                let mode = guard.current_mode;
                let enabled = guard.current_enabled;
                drop(guard);

                // Update icon.
                indicator_for_attach
                    .set_icon_full(if enabled { ICON_ON } else { ICON_OFF }, "vi-im");

                // Rebuild menu with new state.
                let new_menu = build_menu(
                    &indicator_for_attach,
                    &state_for_attach,
                    &config_path_for_attach,
                    &settings_exe_for_attach,
                    method,
                    mode,
                    enabled,
                );
                indicator_for_attach.set_menu(Some(&new_menu));

                glib::ControlFlow::Continue
            });

            // External config poller (detects changes from CLI, settings GUI, manual edits).
            let watch_path = config_path_for_gtk.clone();
            let update_tx_for_poller = update_tx_for_thread.clone();
            thread::spawn(move || {
                let mut last = read_state(&watch_path);
                info!("[TRAY] External poller started, watching: {:?}", watch_path);
                loop {
                    thread::sleep(Duration::from_secs(2));
                    let now = read_state(&watch_path);
                    if now != last {
                        info!("[TRAY] External change detected: {:?} -> {:?}", last, now);
                        last = now;
                        let _ = update_tx_for_poller.send(UpdateSignal);
                    }
                }
            });

            // Run GTK main loop.
            info!("[TRAY] GTK main loop starting");
            gtk::main();
            info!("[TRAY] GTK main loop exited");
        })
        .expect("Failed to spawn GTK thread");

    info!("[TRAY] Ayatana AppIndicator tray registered (GTK thread)");
    update_tx
}
